import { ApplicationTrackingDTO } from "./application_tracking.interface";
import { ApplicationStatus, EntityStatus } from "./enum.interface";
import { ExtractedDependentDTO } from "./extracted_dependent.interface";
import { BaseResponse } from "./shared.interface";

export interface ExtractedTemporaryLossApplicationDTO {
  id?: number;
  full_name?: string;
  full_name_confidence?: number;
  id_number?: string;
  id_number_confidence?: number;
  date_of_birth?: Date;
  date_of_birth_confidence?: number;
  contact_number?: string;
  contact_number_confidence?: number;
  email?: string;
  email_confidence?: number;
  address?: string;
  address_confidence?: number;
  nok_full_name?: string;
  nok_full_name_confidence?: number;
  nok_contact_number?: string;
  nok_contact_number_confidence?: number;
  bank_name?: string;
  bank_name_confidence?: number;
  account_number?: string;
  account_number_confidence?: number;
  branch_code?: string;
  branch_code_confidence?: number;
  existing_insurance_with_other_company?: string;
  existing_insurance_with_other_company_confidence?: number;
  existing_chronic_condition?: string;
  existing_chronic_condition_confidence?: number;
  agent_full_name?: string;
  agent_full_name_confidence?: number;
  agent_number?: string;
  agent_number_confidence?: number;
  title?: string;
  title_confidence?: number;
  gender?: string;
  gender_confidence?: number;
  b_date_of_birth?: Date;
  b_date_of_birth_confidence?: number;
  claim_ailment?: string;
  claim_ailment_confidence?: number;
  claim_amount?: string;
  claim_amount_confidence?: number;
  declined_coverage?: string;
  declined_coverage_confidence?: number;
  declined_cover_reason?: string;
  declined_cover_reason_confidence?: number;
  overall_accuracy?: number;
  status?: ApplicationStatus;
  date_created?: Date;
  date_updated?: Date;
  entity_status?: EntityStatus;

  extracted_dependents?: ExtractedDependentDTO[];
  application_tracking_stages?: ApplicationTrackingDTO[];
}

export interface ExtractedTemporaryLossApplicationCreateRequest {
  full_name?: string;
  full_name_confidence?: number;
  id_number?: string;
  id_number_confidence?: number;
  date_of_birth?: Date;
  date_of_birth_confidence?: number;
  contact_number?: string;
  contact_number_confidence?: number;
  email?: string;
  email_confidence?: number;
  address?: string;
  address_confidence?: number;
  nok_full_name?: string;
  nok_full_name_confidence?: number;
  nok_contact_number?: string;
  nok_contact_number_confidence?: number;
  bank_name?: string;
  bank_name_confidence?: number;
  account_number?: string;
  account_number_confidence?: number;
  branch_code?: string;
  branch_code_confidence?: number;
  existing_insurance_with_other_company?: string;
  existing_insurance_with_other_company_confidence?: number;
  existing_chronic_condition?: string;
  existing_chronic_condition_confidence?: number;
  agent_full_name?: string;
  agent_full_name_confidence?: number;
  agent_number?: string;
  agent_number_confidence?: number;
  title?: string;
  title_confidence?: number;
  gender?: string;
  gender_confidence?: number;
  b_date_of_birth?: Date;
  b_date_of_birth_confidence?: number;
  claim_ailment?: string;
  claim_ailment_confidence?: number;
  claim_amount?: string;
  claim_amount_confidence?: number;
  declined_coverage?: string;
  declined_coverage_confidence?: number;
  declined_cover_reason?: string;
  declined_cover_reason_confidence?: number;
  overall_accuracy?: number;
}

export interface ExtractedTemporaryLossApplicationUpdateRequest {
  full_name?: string;
  full_name_confidence?: number;
  id_number?: string;
  id_number_confidence?: number;
  date_of_birth?: Date;
  date_of_birth_confidence?: number;
  contact_number?: string;
  contact_number_confidence?: number;
  email?: string;
  email_confidence?: number;
  address?: string;
  address_confidence?: number;
  nok_full_name?: string;
  nok_full_name_confidence?: number;
  nok_contact_number?: string;
  nok_contact_number_confidence?: number;
  bank_name?: string;
  bank_name_confidence?: number;
  account_number?: string;
  account_number_confidence?: number;
  branch_code?: string;
  branch_code_confidence?: number;
  existing_insurance_with_other_company?: string;
  existing_insurance_with_other_company_confidence?: number;
  existing_chronic_condition?: string;
  existing_chronic_condition_confidence?: number;
  agent_full_name?: string;
  agent_full_name_confidence?: number;
  agent_number?: string;
  agent_number_confidence?: number;
  title?: string;
  title_confidence?: number;
  gender?: string;
  gender_confidence?: number;
  b_date_of_birth?: Date;
  b_date_of_birth_confidence?: number;
  claim_ailment?: string;
  claim_ailment_confidence?: number;
  claim_amount?: string;
  claim_amount_confidence?: number;
  declined_coverage?: string;
  declined_coverage_confidence?: number;
  declined_cover_reason?: string;
  declined_cover_reason_confidence?: number;
  overall_accuracy?: number;
  status?: ApplicationStatus;
}

export interface ExtractedTemporaryLossApplicationResponse extends BaseResponse {
  extractedLemporaryLossApplication?: ExtractedTemporaryLossApplicationDTO;
  extractedTemporaryLossApplications?: ExtractedTemporaryLossApplicationDTO[];
}