from datetime import date
from Model.UserModel import UserCreateRequest
from Utils.Enums import UserRole

users_to_seed = [
    UserCreateRequest(
        id_number="75-191961 R 00",
        email="andrew@gmail.com",
        first_name="ANDREW",
        last_name="ROBERTS",
        other_names="WILLIAM L",
        user_role=UserRole.ADMIN,
        date_of_birth=date(1959, 11, 17),
        village_of_origin="",
        place_of_birth="HARARE",
        phone_number=None,
        address=None,
        password="admin123"
    ),
    UserCreateRequest(
        id_number="63-758552 Y 27",
        email="mutumwa@gmail.com",
        first_name="MUTUMWA",
        last_name="DZIVA",
        other_names="MAWER",
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1960, 11, 1),
        village_of_origin="BINDUR",
        place_of_birth="MAWERE",
        phone_number=None,
        address=None,
        password="passworddd"
    ),
    UserCreateRequest(
        id_number="75-2033056J42",
        email="brandon@gmail.com",
        first_name="TONDERAI BRANDO",
        last_name="MUTOMBWA",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1994, 4, 3),
        village_of_origin="MUTARE",
        place_of_birth="CHIPUNZA",
        phone_number='0776464136',
        address=None,
        password="passworddd"
    ),
    UserCreateRequest(
        id_number="0101140853082",
        email="liso@gmail.com",
        first_name="LISO",
        last_name="NGWENDU",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(2001, 1, 14),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number="0771234567",
        address="123 Main St, Johannesburg",
        password="password001"
    ),
    UserCreateRequest(
        id_number="91-556677 R 33",
        email="john@gmail.com",
        first_name="JOHN",
        last_name="DOE",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1990, 1, 20),
        village_of_origin="BULAWAYO",
        place_of_birth="BULAWAYO",
        phone_number="0779876543",
        address="456 Side St, Bulawayo",
        password="password002"
    ),
    UserCreateRequest(
        id_number="72-112233 R 44",
        email="sarah@gmail.com",
        first_name="SARAH",
        last_name="CHITEPO",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1985, 12, 5),
        village_of_origin="MASVINGO",
        place_of_birth="MASVINGO",
        phone_number="0777654321",
        address="789 Hill Rd, Masvingo",
        password="admin456"
    ),
    UserCreateRequest(
        id_number="80-998877 R 55",
        email="michael@gmail.com",
        first_name="MICHAEL",
        last_name="TSANGA",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1992, 3, 15),
        village_of_origin="CHIRUMANZU",
        place_of_birth="CHIRUMANZU",
        phone_number="0771112222",
        address=None,
        password="password003"
    ),
    UserCreateRequest(
        id_number="79-887766 R 66",
        email="unknown@gmail.com",
        first_name="ANNA",
        last_name="MUGABE",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1995, 6, 18),
        village_of_origin="MASVINGO",
        place_of_birth="MASVINGO",
        phone_number="0773334444",
        address=None,
        password="password004"
    ),
    UserCreateRequest(
        id_number="88-665544 R 77",
        email="bob@gmail.com",
        first_name="BOB",
        last_name="CHIKWIRIRI",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1980, 9, 12),
        village_of_origin="BULAWAYO",
        place_of_birth="BULAWAYO",
        phone_number=None,
        address=None,
        password="admin789"
    ),
    UserCreateRequest(
        id_number="95-443322 R 88",
        email="alice@gmail.com",
        first_name="ALICE",
        last_name="MUGABE",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(2000, 2, 25),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number="0775556666",
        address="12 Sunset Blvd, Harare",
        password="password005"
    ),
    UserCreateRequest(
        id_number="60-123456 R 99",
        email="unknown@example.com",
        first_name="TONI",
        last_name="CHINHARA",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1999, 12, 5),
        village_of_origin="MASVINGO",
        place_of_birth="MASVINGO",
        phone_number=None,
        address=None,
        password="password006"
    ),
    UserCreateRequest(
        id_number="77-112244 R 11",
        email="peter@gmail.com",
        first_name="PETER",
        last_name="MUBVUMIRE",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1978, 5, 30),
        village_of_origin="BINDURA",
        place_of_birth="BINDURA",
        phone_number="0777778888",
        address=None,
        password="admin001"
    ),
    UserCreateRequest(
        id_number="76-334455 R 22",
        email="rachel@gmail.com",
        first_name="RACHEL",
        last_name="TSANGA",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1993, 4, 10),
        village_of_origin="CHIRUMANZU",
        place_of_birth="CHIRUMANZU",
        phone_number="0778889999",
        address="34 Green St, Chirumanzu",
        password="password007"
    ),
    UserCreateRequest(
        id_number="81-556677 R 33",
        email="george@gmail.com",
        first_name="GEORGE",
        last_name="CHIKWIRIRI",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1987, 8, 22),
        village_of_origin="BULAWAYO",
        place_of_birth="BULAWAYO",
        phone_number="0779990000",
        address=None,
        password="password008"
    ),
    UserCreateRequest(
        id_number="92-778899 R 44",
        email="faith@gmail.com",
        first_name="FAITH",
        last_name="MUGABE",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1983, 11, 11),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number="0780001111",
        address=None,
        password="admin002"
    ),
    UserCreateRequest(
        id_number="93-889900 R 55",
        email="unknown@example.com",
        first_name="LISA",
        last_name="NGWENDU",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(2001, 1, 14),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number=None,
        address=None,
        password="password009"
    ),
    UserCreateRequest(
        id_number="94-990011 R 66",
        email="maggie@gmail.com",
        first_name="MAGGIE",
        last_name="CHITEPO",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1996, 7, 9),
        village_of_origin="MASVINGO",
        place_of_birth="MASVINGO",
        phone_number="0781112222",
        address="101 Hill Rd, Masvingo",
        password="password010"
    ),
    UserCreateRequest(
        id_number="95-112233 R 77",
        email="daniel@gmail.com",
        first_name="DANIEL",
        last_name="MUBVUMIRE",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1991, 5, 14),
        village_of_origin="BINDURA",
        place_of_birth="BINDURA",
        phone_number="0782223333",
        address=None,
        password="password011"
    ),
    UserCreateRequest(
        id_number="96-223344 R 88",
        email="grace@gmail.com",
        first_name="GRACE",
        last_name="TSANGA",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1988, 10, 30),
        village_of_origin="CHIRUMANZU",
        place_of_birth="CHIRUMANZU",
        phone_number="0783334444",
        address=None,
        password="admin003"
    ),
    UserCreateRequest(
        id_number="97-334455 R 99",
        email="unknown@example.com",
        first_name="LINO",
        last_name="CHIKWIRIRI",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1992, 9, 7),
        village_of_origin="BULAWAYO",
        place_of_birth="BULAWAYO",
        phone_number=None,
        address=None,
        password="password012"
    ),
    UserCreateRequest(
        id_number="98-445566 R 00",
        email="karen@gmail.com",
        first_name="KAREN",
        last_name="MUGABE",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1994, 2, 2),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number="0784445555",
        address=None,
        password="password013"
    ),
    UserCreateRequest(
        id_number="99-556677 R 11",
        email="unknown@example.com",
        first_name="TONI",
        last_name="CHINHARA",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1999, 12, 5),
        village_of_origin="MASVINGO",
        place_of_birth="MASVINGO",
        phone_number=None,
        address=None,
        password="password014"
    ),
    UserCreateRequest(
        id_number="100-667788 R 22",
        email="victor@gmail.com",
        first_name="VICTOR",
        last_name="MUBVUMIRE",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1979, 3, 12),
        village_of_origin="BINDURA",
        place_of_birth="BINDURA",
        phone_number="0785556666",
        address=None,
        password="admin004"
    ),
    UserCreateRequest(
        id_number="101-778899 R 33",
        email="zoe@gmail.com",
        first_name="ZOE",
        last_name="TSANGA",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1993, 6, 21),
        village_of_origin="CHIRUMANZU",
        place_of_birth="CHIRUMANZU",
        phone_number="0786667777",
        address=None,
        password="password015"
    ),
    UserCreateRequest(
        id_number="102-889900 R 44",
        email="unknown@example.com",
        first_name="LISO",
        last_name="NGWENDU",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(2001, 1, 14),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number=None,
        address=None,
        password="password016"
    ),
    UserCreateRequest(
        id_number="103-990011 R 55",
        email="steve@gmail.com",
        first_name="STEVE",
        last_name="CHITEPO",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1985, 12, 5),
        village_of_origin="MASVINGO",
        place_of_birth="MASVINGO",
        phone_number="0787778888",
        address=None,
        password="admin005"
    ),
    UserCreateRequest(
        id_number="104-112233 R 66",
        email="emma@gmail.com",
        first_name="EMMA",
        last_name="MUBVUMIRE",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1991, 5, 14),
        village_of_origin="BINDURA",
        place_of_birth="BINDURA",
        phone_number="0788889999",
        address=None,
        password="password017"
    ),
    UserCreateRequest(
        id_number="105-223344 R 77",
        email="unknown@example.com",
        first_name="LISA",
        last_name="NGWENDU",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(2001, 1, 14),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number=None,
        address=None,
        password="password018"
    ),
    UserCreateRequest(
        id_number="106-334455 R 88",
        email="paul@gmail.com",
        first_name="PAUL",
        last_name="CHIKWIRIRI",
        other_names=None,
        user_role=UserRole.CUSTOMER,
        date_of_birth=date(1992, 9, 7),
        village_of_origin="BULAWAYO",
        place_of_birth="BULAWAYO",
        phone_number="0789990000",
        address=None,
        password="password019"
    ),
    UserCreateRequest(
        id_number="107-445566 R 99",
        email="linda@gmail.com",
        first_name="LINDA",
        last_name="MUGABE",
        other_names=None,
        user_role=UserRole.ADMIN,
        date_of_birth=date(1983, 11, 11),
        village_of_origin="HARARE",
        place_of_birth="HARARE",
        phone_number="0790001111",
        address=None,
        password="admin006"
    )
]
